[package]
name = "centralized-file-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = { version = "0.7.5"}
serde = { version = "1.0", features = ["derive"] }